version: '3'
services:
  db:
    image: postgres
# https://medium.com/@asuarezaceves/initializing-a-postgresql-database-with-a-dataset-using-docker-compose-a-step-by-step-guide-3feebd5b1545
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
#    environment:
#      POSTGRES_PASSWORD: admin
#      POSTGRES_USER: postgres
#      POSTGRES_DB: practice
    ports:
      - "5432:5432"
    networks:
      - webchz
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/backend-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/practice
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - webchz

networks:
  webchz:
    driver: bridge

