@baseURL=http://localhost:3001/api
###
# @name registerPatient1
POST {{baseURL}}/sign-up HTTP/1.1
Content-Type: application/json

    {
    "email": "patient17@email.com",
    "password": "patient114",
    "role": "patient"
    }

###
# @name registerPatient2
POST {{baseURL}}/register HTTP/1.1
Content-Type: application/json

    {
    "email": "patient21@email.com",
    "password": "patient21",
    "name": "patient2"
    }

###
# @name registerPatient3
POST {{baseURL}}/register HTTP/1.1
Content-Type: application/json

    {
    "email": "patient3@email.com",
    "password": "patient3"
    }

###
# @name registerAdmin
POST {{baseURL}}/register HTTP/1.1
Content-Type: application/json

    {
    "email": "admin@email.com",
    "password": "admin"
    }

###
# @name registerGP
POST {{baseURL}}/register HTTP/1.1
Content-Type: application/json

    {
    "email": "GP1@email.com",
    "password": "generalP1"
    }

###
# @name selfRegister1
POST {{baseURL}}/patient/self-reg HTTP/1.1
Content-Type: application/json

{
    "name": "patient2",
    "condition": "fine"
}

### @name getSelfReg
GET {{baseURL}}/admin/approvals HTTP/1.1

###

# PATCH  {{baseURL}}/admin/approve HTTP/1.1
### @name adminApprove
PATCH  {{baseURL}}/admin/approve/1 HTTP/1.1
Content-Type: application/json

{
    "status": "cr"
}

###
### @name getValidPatients
GET  {{baseURL}}/patient/guest-check/24 HTTP/1.1
###

# @name patchGuestPatient
PATCH  {{baseURL}}/guestPatient/24 HTTP/1.1

Content-Type: application/json

{
    "id":24,
    "patientId": 24,
    "ifPatientValid": "11"
}
###

# @name checkGuest
PATCH {{baseURL}}/patient/guest-check/24 HTTP/1.1
Content-Type: application/json

{
    "ifPatientValid": "flase"
}
###

### ---------testing------------------

### @name get gps
GET {{baseURL}}/gpss HTTP/1.1
###

### @name getSlots
GET {{baseURL}}/gpss/1/slots/ HTTP/1.1
###

#TODO verifications: user is bookedById,.....
### @name bookSlot
PATCH {{baseURL}}/slots/2 HTTP/1.1
Content-Type: application/json

{
    "bookedByPID": "002",
    "status":"hold"
}
###