version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: practice
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/your-app-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/practice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin


